version: 2.1

jobs:
  deploy:
    docker:
      - image: circleci/node:stretch
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install rsync
      - add_ssh_keys
      - run: ssh-keyscan -H necro.tech >> ~/.ssh/known_hosts
      - run: rsync -va --exclude '.git' --exclude '.circleci' --delete ./ shaun@necro.tech:/var/www/necro.tech/public_html

workflows:
  Deploy:
    jobs:
      - deploy
